services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_DB=${DB_URL}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - KEY_TOKEN=${KEY_TOKEN}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - KEY_TOKEN=${KEY_TOKEN}
    ports:
      - "8080:8080"

volumes:
  db_data:

